id: P003090
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG23650
  title: རྩོད་ལན་གྱི་རིམ་ཕྱོགས་གཅིག་ཏུ་བསྡེབས་པ་ཐུབ་བསྟན་བྱི་དོར།
  author: ''
  volumes:
    21e62b881e2f4040b825bc83aab71ef0:
      image_group_id: I1KG23727
      title: ''
      volume_number: 1
      total_pages: 282
      base_file: v001.txt
