id: I04B42AB8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T03:17:26+00:00'
last_modified: '2022-06-07T17:29:36.545368+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23650
  title: རྩོད་ལན་གྱི་རིམ་ཕྱོགས་གཅིག་ཏུ་བསྡེབས་པ་ཐུབ་བསྟན་བྱི་དོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E777:
      image_group_id: I1KG23727
      title: ''
      total_pages: 282
      order: 1
      base_file: E777.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
